console.log("this  my resume");
  
myResume=  

    "basics": {
      "name": "RAGU P",
      "email": "ragusai0500@.com",
      "phone": 9941728099,
      "degree": "B.E",
      "location": {
        "address": "7937(tnhb),ayapakkam",
        "postalCode": 600077,
        "city": "Chennai",
        "state": "Tamilnadu",
             },
    "work": [
      {
        "company": "jnm PVT",
        "position": "sales Executive",
        "startDate": "2022-03-18",
           
        "summary": "i am the sales executive handling various task and gaining lots of experience",
      }
    ],
    "education": [
      {
        "institution": "Karur College Of Engineering",
        "department": "Mechanical",
        "studyType": "fulltime",
        "batch start year": 2016,
        "batch end year": 2019,
        "gpa": 7.5,
      }
    ],
    "languages": [
      {
        "language": "Tamil,Enlish",
      }
    ],
    "interests": [
      {
        "name": "playing kabadi,",
      }
    ]
  }